### ISSUE TITLE
Bug: After logging in, if I open a new tab and go to http://localhost:8100 it asks me to log in again

### ISSUE THREAD

**Issue by daattali** [curso-r/auth0#20] opened 2019-06-07 18:33 UTC
Downloaded the dev version from today and seeing this behaviour.

**Comment by jtrecenti** [comment] 2019-06-09 14:48
I can't reproduce this issue in normal tabs, but it happens (and the expected behavior) in incognito/private tabs. Did you open an incognito tab?

**Comment by daattali** [comment] 2019-06-09 14:53
No, this was happening in regular chrome, with cookies and everything allowed. I'll try to reproduce

**Comment by daattali** [comment] 2019-06-09 16:34
Just tried again, and it is happening.
https://imgur.com/a/74vpmuX

**Comment by jtrecenti** [comment] 2019-06-09 20:40
I managed to reproduce the problem using google authentication. Apparently when I use user-data-base login it works as expected. Maybe it's related do #8 .

**Comment by jtrecenti** [comment] 2019-06-09 21:36
Curiously, if I go to the "Universal Login" section and choose the "New (beta)" option, it just works. Maybe it is not a problem in the package at all :/

https://imgur.com/a/nPrewVG

**Comment by jtrecenti** [comment] 2019-09-16 01:05
I'm closing as it is an Auth0's bug and I the new universal login doesn't have this bug.

**Closed by jtrecenti** 2019-09-16 01:05 UTC
Labels: bug, solved-review
